version: '3.8'
services:
  movies:
    image: arjun101010/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: arjun101010/arjungowda.online:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: arjun101010/movies_ticket:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: arjun101010/train_ticket:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
